import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavContext from "@/context/NavContext";
import Stairs from "@/components/common/Stairs";
import Navbar from "@/components/Navigation/Navbar";
import FullScreenNav from "@/components/Navigation/FullScreenNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavContext>
          <Stairs>
            <Navbar />
            {children}
            <FullScreenNav />
          </Stairs>
        </NavContext>
      </body>
    </html>
  );
}
